spring.application.name=emt-lab1

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/emt_lab1
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - validate ?? ????????? ????????, ?? ?? ???????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

app.refresh.interval=3600000

spring.flyway.validate-on-migrate=false
jwt.secret=mySuperSecretKeyForJWTThatIsLongEnough123
jwt.expiration=86400000
